var tableauQuestion = [
    {   question : "Se você está dirigindo a 80 km/h, e você entra em uma área residencial, isso significa que",
        propositionA : "Você deverá aumentar a velocidade",
        propositionB : "Você pode acelerar enquanto não há nenhum carro à frente",
        propositionC : "Você deve reduzir a velocidade",
        propositionD : "Você pode manter a velocidade",
        reponse : "C"},
		
    {   question : "Enquanto você está virando à esquerda no semáforo verde, você vê um pedestre atravessando na faixa. Quem tem o direito de continuar?",
        propositionA : "O pedestre, porque ele pode atravessar com qualquer sinal",
        propositionB : "Seu veículo, porque está verde para você",
        propositionC : "O pedestre, pois os pedestres sempre têm o direito de passagem",
        propositionD : "Seu veículo, pois os veículos sempre têm o direito de passagem",
        reponse : "C"},
		
    {   question : "A menos que informado, a velocidade máxima na área residencial é de ____ km/h.",
        propositionA : "50",
        propositionB : "55",
        propositionC : "65",
        propositionD : "70",
        reponse : "A"},
	
	{   question : "Antes de qualquer mudança de faixa, você deve",
        propositionA : "Checar os retrovisores",
        propositionB : "Checar os pontos cegos",
        propositionC : "Dar seta",
        propositionD : "Todas acima",
        reponse : "D"},
		
	{   question : "Qual a porcentagem de álcool no sangue para que seja declarado embriagado?",
        propositionA : "0.05%",
        propositionB : "0.18%",
        propositionC : "0.08%",
        propositionD : "0.06%",
        reponse : "C"},
		
	{   question : "Você deve ir ao acostamento e parar até que qualquer veículo de emergência com sirene tenha passado, a menos que:",
        propositionA : "Você esteja apressado",
        propositionB : "Haja espaço suficiente na outra faixa",
        propositionC : "Você esteja na área escolar",
        propositionD : "Você esteja em um cruzamento",
        reponse : "D"},
	
	{   question : "Direito de passagem deve ser cedido aos veículos de emergência",
        propositionA : "Sempre",
        propositionB : "Piscando vermelho, azul ou luzes brancas",
        propositionC : "Usando a sirene ou piscando vermelho, azul ou luzes brancas",
        propositionD : "Usando a sirene",
        reponse : "C"},
		
	{   question : "Qual a seguir é permetido na ultrapassagem de veículo?",
        propositionA : "Seguindo de perto",
        propositionB : "Saindo da pista principal",
        propositionC : "Dirigindo no lado oposto da pista",
        propositionD : "Excedindo o limite de velocidade",
        reponse : "C"},
		
	{   question : "Você está dirigindo em uma pista livre em que o limite de velocidade é de 110 km/h. A maiorida dos veículos estão viajando a 120 km/h, portanto você deve dirigir não mais que a:",
        propositionA : "80 km/h",
        propositionB : "40 km/h",
        propositionC : "50 km/h",
        propositionD : "110 km/h",
        reponse : "D"},
		
	{   question : "Quando você está sendo ultrapassado por um veículo, é importante NÃO:",
        propositionA : "Diminuir a velocidade",
        propositionB : "Checar os retrovisores",
        propositionC : "Olhar para o outro motorista",
        propositionD : "Aumentar a velocidade",
        reponse : "D"},
]
